### ISSUE TITLE
SSR Question / Error: Angular 7 + docs example results in AlgoliaSearchUnknownError

### ISSUE THREAD

**Issue by pjr0001** [algolia/angular-instantsearch#379]
Describe the bug 🐛

2 things: 

**1) When following the example here: https://community.algolia.com/angular-instantsearch/guides/server-side-rendering.html I get the following server side error:**

```  name: 'AlgoliaSearchUnknownError',
  message: 'Unknown error occured',
  debugData:
   [ { currentHost: 'https://<removed>-dsn.algolia.net',
       headers: [Object],
       content:
        '{"requests":[{"indexName":"<removed>","params":"query=&page=0&highlightPreTag=__ais-highlight__&highlightPostTag=__%2Fais-highlight__&facets=%5B%5D&tagFilters="}]}',
       contentLength: 177,
       method: 'POST',
       timeouts: [Object],
       url: '/1/indexes/*/queries',
       startTime: 2018-11-18T02:14:56.414Z,
       endTime: 2018-11-18T02:14:56.415Z,
       duration: 1 } ] }
```
trace
```
ERROR { AlgoliaSearchUnknownError: Unknown error occured
    at tryFallback (/Users/cwd/dist/server.js:232925:15)
    at ZoneDelegate.invoke (/Users/cwd/dist/server.js:531:26)
    at Object.onInvoke (/Users/cwd/dist/server.js:18006:33)
    at ZoneDelegate.invoke (/Users/cwd/dist/server.js:530:32)
    at Zone.run (/Users/cwd/dist/server.js:281:43)
    at /Users/cwd/dist/server.js:1015:34
    at ZoneDelegate.invokeTask (/Users/cwd/dist/server.js:564:31)
    at Object.onInvokeTask (/Users/cwd/dist/server.js:17997:33)
    at ZoneDelegate.invokeTask (/Users/cwd/dist/server.js:563:36)
    at Zone.runTask (/Users/cwd/dist/server.js:331:47)
```
server.ts
```
app.engine('html', (_, options, callback) => {
  const engine = ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [
      { provide: 'request', useFactory: () => options.req, deps: [] },
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  });
  engine(_, options, callback);
});
```
component config (in my constructor)
```
this.config = {
                searchParameters,
                urlSync: false,
                indexName: `SecuredUser_${environment.name}`,
                searchClient:  createSSRSearchClient({
                    makeStateKey,
                    HttpHeaders,
                    transferState: this.transferState,
                    httpClient: this.httpClient,
                    appId: '<removed>',
                    apiKey: '<removed>'
                })
            };
```

**2) What is the point of createSSRSearchClient vs the standard config? Specificially, is there a simple reason why SSR doesn't "just work" with a standard implementation of instant search?** 

To Reproduce 🔍
check out this commit (which still contains webpack): https://github.com/angular/universal-starter/commit/d85b67038a18b0a2cc20e7eb8e1b9964b413ebea

update deps in package.json to latest angular versions

follow the docs:  https://community.algolia.com/angular-instantsearch/guides/server-side-rendering.html

**Comment by tkrugg** [comment]
Hi @pjr0001 
We currently support SSR up to angular@v5. Supporting v7 is something we definitely want (help is welcome 🥇 ) but don't do yet at the moment.
