### ISSUE TITLE
Unexpected identifier - import InstantSearch from './lib/InstantSearch';

### ISSUE THREAD

**Issue by emok032** [algolia/angular-instantsearch#555]
Receiving the following error on running server. The application is Angular 7 with an Angular Universal SSR on initial load (for SEO). But client is Angular 7. Cannot find any solutions related to this issue. 
We are evaluating Algolia for our long-term needs. Upgrading our web app, which requires a long-term site search feature.  Thanks for your time.

Followed instructions on:
1. https://www.algolia.com/doc/guides/building-search-ui/getting-started/angular/
2. https://www.algolia.com/doc/guides/building-search-ui/installation/angular/

"ng serve" runs fine without errors.
"npm run build" runs fine without errors.
"nodemon --ignore 'src/*' --exec 'ts-node' server.ts" produces the following error in the command line/terminal:

.../node_modules/instantsearch.js/es/index.js:1 
(function (exports, require, module, __filename, __dirname) { import InstantSearch from './lib/InstantSearch'; 
^^^^^^^^^^^^^ 

SyntaxError: Unexpected identifier 
at new Script (vm.js:79:7) 
at createScript (vm.js:251:10) 
at Object.runInThisContext (vm.js:303:10) 
at Module._compile (internal/modules/cjs/loader.js:657:28) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) 
at Module.load (internal/modules/cjs/loader.js:599:32) 
at tryModuleLoad (internal/modules/cjs/loader.js:538:12) 
at Function.Module._load (internal/modules/cjs/loader.js:530:3) 
at Module.require (internal/modules/cjs/loader.js:637:17) 
at require (internal/modules/cjs/helpers.js:20:18) 
at algoliasearchProxy__default (/Users/eric.mok/Documents/GARP/apps/garpwebsite2.0/node_modules/angular-instantsearch/bundles/angular-instantsearch.umd.js:2:116) 
at Object. (/Users/eric.mok/Documents/GARP/apps/garpwebsite2.0/node_modules/angular-instantsearch/bundles/angular-instantsearch.umd.js:5:2) 
at Module._compile (internal/modules/cjs/loader.js:689:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) 
at Module.load (internal/modules/cjs/loader.js:599:32) 
at tryModuleLoad (internal/modules/cjs/loader.js:538:12) 
at Function.Module._load (internal/modules/cjs/loader.js:530:3) 
at Module.require (internal/modules/cjs/loader.js:637:17) 
at require (internal/modules/cjs/helpers.js:20:18) 
at Object.angular-instantsearch (/Users/eric.mok/Documents/GARP/apps/garpwebsite2.0/dist/server/webpack:/external "angular-instantsearch":1:1) 
at __webpack_require__ (/Users/eric.mok/Documents/GARP/apps/garpwebsite2.0/dist/server/webpack:/webpack/bootstrap:19:1) 
at Object../node_modules/angular-instantsearch/angular-instantsearch.ngfactory.js (/Users/eric.mok/Documents/GARP/apps/garpwebsite2.0/dist/server/main.js:443:12)

**Comment by Haroenv** [comment]
Can you replicate this in a GitHub repo, with full setup? It’s likely something you didn’t set up on the webpack side.

**Comment by emok032** [comment]
Unfortunately I cannot, there is proprietary information in there.  Any
idea which part of Webpack I should look at?

**Comment by Haroenv** [comment]
the issue likely lies with something called "nodeExternalsWhitelist", which would make sure that our code also goes through babel as expected. 

You can create a repo with just your webpack setup and how it integrates with Angular InstantSearch though, no need to add the rest of your code

**Comment by emok032** [comment]
Thanks! I'll do that and send you a link.

**Comment by emok032** [comment]
Here is the repo to our webpack config:

https://github.com/emok032/Algolia-Webpack-Issue/blob/master/webpack.server.config.js

Thanks again.

Eric

**Comment by Haroenv** [comment]
on this line, you need to also add `instantsearch.js` & `angular-instantseach` https://github.com/emok032/Algolia-Webpack-Issue/blob/master/webpack.server.config.js#L13

**Comment by emok032** [comment]
I added it like so.  Is this correct? I'm still getting the same
SyntaxError.

[image: Screen Shot 2019-05-15 at 10.14.45 AM.png]

**Comment by emok032** [comment]
Ignore that typo on Line 15 I corrected the spelling.  Error still occurs
though.

**Comment by Haroenv** [comment]
Is there a possibility you can change the GitHub repo to also include enough to run, a similar kind of scaffold as you'd have in your app

**Comment by emok032** [comment]
No problem, just added some more.  Let me know if you need anything else.

**Comment by Haroenv** [comment]
Looks like this doesn't build for unrelated to Angular InstantSearch (files not being at the right spot), as well as `/^instantsearch.js/` & `/^angular-instantsearch/` not being in the node externals whitelist. 

Could you fix those issues?

**Comment by emok032** [comment]
Sure thing.  I just fixed the white list.  As for the files, I don't have them in their respective parent folders (too many to mimic).  I had just put them in the same root folder of the repo to share the code in it.  Let me know what you think.

**Comment by Haroenv** [comment]
what I mean is that there's too much files for me to properly debug this, since they aren't in the correct spots :)

**Comment by emok032** [comment]
I understand.  What can I do to help?

**Comment by Haroenv** [comment]
A minimal example, which _only_ has the error with misconfigured node externals (or something else) which causes the error you described in the original issue :)

**Comment by emok032** [comment]
Sure, however, the problem is that I don't know what causes the error.  Can you suggest some possible files you might need? I can create a private repo for you without any proprietary information.  But if you could tell me what kind of files at minimum, that would be great.  Thanks again.

**Comment by emok032** [comment]
Is Angular InstantSearch compatible with server-side rendering?

**Comment by tkrugg** [comment]
Yes it is. 
We have written a guide than helps set it up.
https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/angular/

We have a fully working example base on Angular Universal Starter:
Angular InstantSearch V2: https://github.com/algolia/angular-instantsearch/tree/develop/examples/server-side-rendering
Angular InstantSearch V3 (beta): https://github.com/algolia/angular-instantsearch/tree/v3/examples/server-side-rendering

**Comment by tkrugg** [comment]
Hi @emok032. i'm closing this for now, feel free to reopen if you're still experiencing issues.
