### ISSUE TITLE
NullInjectorError: No provider for NgAisInstantSearch!  

### ISSUE THREAD

**Issue by filol** [algolia/angular-instantsearch#701]
**Describe the bug 🐛**

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[AutocompleteComponent -> NgAisInstantSearch]: 
  StaticInjectorError(Platform: core)[AutocompleteComponent -> NgAisInstantSearch]: 
    NullInjectorError: No provider for NgAisInstantSearch!
    at NullInjector.get (http://localhost:4200/vendor.js:59947:27)
    at resolveToken (http://localhost:4200/vendor.js:74865:24)
    at tryResolveToken (http://localhost:4200/vendor.js:74791:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:74641:20)
    at resolveToken (http://localhost:4200/vendor.js:74865:24)
    at tryResolveToken (http://localhost:4200/vendor.js:74791:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:74641:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:85828:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:86894:16)
    at resolveDep (http://localhost:4200/vendor.js:87425:45)
```

**To Reproduce 🔍**

**app.module.ts**
```
imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatOptionModule,
    MatAutocompleteModule,
    MatInputModule,
    NgAisModule.forRoot(),
  ],
```

**app-routings.module.ts**
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import {HomeComponent} from './components/home/home.component';
import {UserProfilComponent} from './components/user-profil/user-profil.component';
import {GoodPracticesComponent} from './components/good-practices/good-practices.component';
import {GoodPracticesDetailsComponent} from './components/good-practices/good-practices-details/good-practices-details.component';
import {LoginComponent} from './components/login/login.component';
import {SearchComponent} from './components/search/search.component';

const routes: Routes = [
  { path: 'search/:category', component: SearchComponent },
  { path: 'search', component: SearchComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

**autocomplete.component.ts**
```
import {Component, EventEmitter, forwardRef, Inject, OnInit, Output} from '@angular/core';
import {BaseWidget, NgAisInstantSearch} from 'angular-instantsearch';
import {connectAutocomplete} from 'instantsearch.js/es/connectors';

@Component({
  selector: 'app-autocomplete',
  templateUrl: './autocomplete.component.html',
  styleUrls: ['./autocomplete.component.scss']
})
export class AutocompleteComponent extends BaseWidget implements OnInit {
  state: {
    query: string;
    // tslint:disable-next-line:ban-types
    refine: Function;
    indices: object[];
  };

  // tslint:disable-next-line:no-output-on-prefix
  @Output() onQuerySuggestionClick = new EventEmitter<{ query: string }>();

  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super('AutocompleteComponent');
  }

  public handleChange($event: KeyboardEvent) {
    this.state.refine(($event.target as HTMLInputElement).value);
  }

  public ngOnInit() {
    this.createWidget(connectAutocomplete, {});
    super.ngOnInit();
  }
}
```

**search.component.ts**
```
import {Component, OnInit} from '@angular/core';
import algoliasearch from 'algoliasearch/lite';

const searchClient = algoliasearch(
  'blabla',
  'blabla'
);

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {

  public config = {
    indexName: 'best-practices',
    searchClient,
    routing: true
  };

  public searchParameters = {
    query: ''
  };

  public setQuery({ query }: { query: string }) {
    this.searchParameters.query = query;
  }

  constructor() {
  }

  ngOnInit() {
  }

}
```

**Expected behavior 💭**

No errors 

**Environment:**
```
"algoliasearch": "^3.35.1",
"angular-instantsearch": "^3.0.0-beta.4",
 "instantsearch.css": "^7.3.1",
 "instantsearch.js": "^4.1.1"
```

**Comment by tkrugg** [comment]
Hi @filol please use instantsearch@3 for now with Angular InstantSearch@3-beta

**Comment by filol** [comment]
Tanks for your answer @tkrugg . You should add it in the initialisation section here : [https://www.algolia.com/doc/guides/building-search-ui/getting-started/angular/](https://www.algolia.com/doc/guides/building-search-ui/getting-started/angular/ )

But unfortunately it still doesn't work and I still get the same error

**Comment by Haroenv** [comment]
Could you create a  GitHub repo with this reproducible failure @filol? Can you see any  difference between what you have and e.g. this example: https://github.com/algolia/angular-instantsearch/tree/v3/examples/e-commerce

**Comment by filol** [comment]
There is the repo : [https://github.com/filol/algolia-test](https://github.com/filol/algolia-test)
The difference I see is that I have a router and I split it up into different components

**Comment by Haroenv** [comment]
What's the reason for closing and reopening the InstantSearch component here? https://github.com/filol/algolia-test/blob/master/src/app/search/search.component.html#L6-L7

**Comment by filol** [comment]
@Haroenv I don't know, i have follow the tuto here : [https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/autocomplete/angular/#results-page-with-autocomplete](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/autocomplete/angular/#results-page-with-autocomplete)

In this tuto they are closing and reopening, i have just copy/past

**Comment by filol** [comment]
@Haroenv Could you find the problem ?
