### ISSUE TITLE
NullInjectorError: No provider for NgAisInstantSearch!

### ISSUE THREAD

**Issue by filol** [algolia/angular-instantsearch#705]
**Describe the bug 🐛**

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[AutocompleteComponent -> NgAisInstantSearch]: 
  StaticInjectorError(Platform: core)[AutocompleteComponent -> NgAisInstantSearch]: 
    NullInjectorError: No provider for NgAisInstantSearch!
    at NullInjector.get (http://localhost:4200/vendor.js:59947:27)
    at resolveToken (http://localhost:4200/vendor.js:74865:24)
    at tryResolveToken (http://localhost:4200/vendor.js:74791:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:74641:20)
    at resolveToken (http://localhost:4200/vendor.js:74865:24)
    at tryResolveToken (http://localhost:4200/vendor.js:74791:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:74641:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:85828:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:86894:16)
    at resolveDep (http://localhost:4200/vendor.js:87425:45)
```

**To Reproduce 🔍**

[https://github.com/filol/algolia-test](https://github.com/filol/algolia-test)

**Expected behavior 💭**

0 Errors :)

**Environment:**

 - OS: mac
 - Browser: chrome
 - Version 79.0.3945.88

**Comment by tkrugg** [comment]
Hi @filol  thanks for providing the code sample.

You've created `autocomplete.component.ts` which is NgAisInstantSearch. That's good but it means everytime you write, `<app-autocomplete><app-autocomplete/>`, you neam to make sure it's wrapped in `<ais-instantsearch></ais-instantsearch/>`.

In your [toolbar component](https://github.com/filol/algolia-test/blob/master/src/app/toolbar/toolbar.component.html#L2), `app-autocomplete` is not wrapped in `ais-instantsearch`. This is why you're seeing an error.

I hope this helps!
